---
# tasks file for nome_da_role
- name: "Adicionando chave apt da HashiCorp"
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
- name: "Instalando repositório HashiCorp"
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present
    update_cache: yes
- name: "Instalando consul"
  apt:
    name: "consul={{ consul_version }}"
    state: present

- name: "Removendo arquivo padrao do consul"
  file:
    path: "/etc/consul.d/consul.hcl"
    state: absent
- name: "Criando o arquivo de configuração"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/consul.d/{{ item }}.tpl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: 0644
  loop:
    - consul.hcl
    - server.hcl
- name: "Criando script de inicialização"
  copy:
    src: consul_bootstrap.sh
    dest: /usr/local/bin/consul_bootstrap.sh
    mode: 0755
